version: "3"
services:
   vprodb:
        image: vprofiledb:V1
        ports:
           - "3306:3306" 
        volumes:
          - vprodbdata:/var/lib/mysql
        environment:
           - MYSQL_ROOT_PASSWORD=vprodbpass
   vprocache01:
         image: memcached
         ports:
           - "11211:11211" 
         depends_on:
                   - "vprodb"    
             
   vpromq01:
       image: rabbitmq
       ports:
         - "15672:15672"  
       environment:
              -  RABBITMQ_DEFAULT_USER=guest
              -  RABBITMQ_DEFAULT_PASS=guest
       depends_on:
            - "vprocache01"         

   vproapp:
      image: vprofileapp:V1
      ports:
       - "8080:8080"
      volumes:
          - vproappdata:/usr/local/tomcat/webapps
      depends_on:
              - "vpromq01"      

   vproweb:
       image: vprofileweb:V1
       ports:
          - "80:80"      
       depends_on:
                - "vproapp"     
            
volumes:      
   vprodbdata: {}
   vproappdata: {}
